name: flutter_ffmpeg_sw_player
description: "一个基于 FFmpeg 管道输出的 Flutter 视频软渲染插件，专为解决 Linux 平台下视频播放的稳定性与依赖痛点而设计。"
version: 0.0.4
repository: https://github.com/debuggerx01/flutter_ffmpeg_sw_player

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  texture_rgba_renderer: any
  ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  linux:
  macos:
  windows:
